# Usar uma imagem base do Python
FROM python:3.11-slim

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar o arquivo de dependências para o diretório de trabalho
COPY requirements.txt requirements.txt

# Instalar as dependências
RUN pip install --no-cache-dir -r requirements.txt

ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_HOST
ARG MYSQL_DATABASE
ARG SECRET_KEY

ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV SECRET_KEY=$SECRET_KEY

# Copiar o código da aplicação para o diretório de trabalho
COPY . .

# Expor a porta em que a aplicação Flask irá rodar
EXPOSE 8080

# Comando para iniciar a aplicação Flask
CMD ["flask", "run", "--host=0.0.0.0"]
