version: "3.9"
services:
  mysql:
    volumes:
    - db:/var/lib/mysql
    - ./mydb.sql:/docker-entrypoint-initdb.d/mydb.sql
    image: mysql:8.0
    container_name: db_container
    restart: always
    environment:
      MYSQL_DATABASE: db_alunos
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 127.0.0.1
    ports:
      - '3306:3306'

volumes:
  db:
    driver: local